[package]
name = "copenclose"
version = "0.2.1"
authors = ["Uchio Kondo <udzura@udzura.jp>"]
edition = "2018"

[dependencies]

libc = "0.2.76"
ctrlc = "3.1.7"
anyhow = "1.0"
libbpf-rs = "0.6.1"
plain = "0.2.3"
chrono = "0.4.19"
structopt = "0.3.21"
